//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksSimplified
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int actionbar_background_end = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int actionbar_background_item_pressed_end = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int actionbar_background_item_pressed_start = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int actionbar_background_start = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int actionbar_separator = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int actionbar_title = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int bottomactionbar_background_end = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int bottomactionbar_background_item_pressed_end = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int bottomactionbar_background_item_pressed_start = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int bottomactionbar_background_start = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int bottomactionbar_separator = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int bottomactionbar_title = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int pop = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int redtext = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_height = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_home_item_width = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_item_height = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_item_width = 2131034114;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_btn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_btn_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_btn_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bottomactionbar_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bottomactionbar_btn = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bottomactionbar_btn_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bottomactionbar_btn_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_add_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_cancel = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_delete_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_microphone = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_overflow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_about = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int actionbar = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int actionbar_actions = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int actionbar_home = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int actionbar_home_bg = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbar_home_btn = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int actionbar_home_is_back = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int actionbar_home_logo = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int actionbar_item = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int actionbar_progress = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int actionbar_title = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int actionbar_title_layout = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int bottomActionbar = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int bottomactionbar_item = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int overflow_spinner = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int screen = 2131230720;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActionBar_Item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BlankSpinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BottomActionBar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BottomActionBar_Item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Other = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OverflowActionBar_Item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SpinnerItem = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int actionbar_activity_not_found = 2131099648;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int ActionBarHomeItem = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int ActionBarHomeLogo = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int ActionBarItem = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int ActionBarProgressBar = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int BottomActionBar = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int MyTheme = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Theme_Splash = 2131165191;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ActionBar_title = 0;
			
			private Styleable()
			{
			}
		}
	}
}
