//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksSimplified
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050006
			public const int actionbar_background_end = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int actionbar_background_item_pressed_end = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int actionbar_background_item_pressed_start = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_background_start = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_separator = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_title = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int bottomactionbar_background_end = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int bottomactionbar_background_item_pressed_end = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int bottomactionbar_background_item_pressed_start = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int bottomactionbar_background_start = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int bottomactionbar_separator = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int bottomactionbar_title = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int gray = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int pop = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int redtext = 2131034113;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_height = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int actionbar_home_item_width = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_item_height = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_item_width = 2131099650;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_btn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_btn_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_btn_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bottomactionbar_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bottomactionbar_btn = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bottomactionbar_btn_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bottomactionbar_btn_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int clear_btn_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int clearbutton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_add = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_cancel = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_delete_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_microphone = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_overflow = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_launcher = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_menu_about = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_menu_delete_all = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int splash = 2130837524;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000c
			public const int actionbar = 2131361804;
			
			// aapt resource value: 0x7f0a0006
			public const int actionbar_actions = 2131361798;
			
			// aapt resource value: 0x7f0a0001
			public const int actionbar_home = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int actionbar_home_bg = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int actionbar_home_btn = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int actionbar_home_is_back = 2131361797;
			
			// aapt resource value: 0x7f0a0002
			public const int actionbar_home_logo = 2131361794;
			
			// aapt resource value: 0x7f0a000a
			public const int actionbar_item = 2131361802;
			
			// aapt resource value: 0x7f0a0008
			public const int actionbar_progress = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int actionbar_title = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int actionbar_title_layout = 2131361799;
			
			// aapt resource value: 0x7f0a000b
			public const int bottomactionbar_item = 2131361803;
			
			// aapt resource value: 0x7f0a0010
			public const int button_add_task = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public const int button_microphone = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int edit_text_new_task = 2131361807;
			
			// aapt resource value: 0x7f0a0013
			public const int menu_about = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int menu_cancel = 2131361813;
			
			// aapt resource value: 0x7f0a0014
			public const int menu_delete = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int menu_delete_all = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int overflow_spinner = 2131361809;
			
			// aapt resource value: 0x7f0a0000
			public const int screen = 2131361792;
			
			// aapt resource value: 0x7f0a000d
			public const int status_text = 2131361805;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActionBar_Item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BlankSpinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BottomActionBar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BottomActionBar_Item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CheckedListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OverflowActionBar_Item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SpinnerItem = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int MainMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MainMenuEdit = 2131296257;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int ApplicationName = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int VersionNumber = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int actionbar_activity_not_found = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int cancel = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int confirm_delete = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int confirm_delete_title = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int loading = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int menu_string_about = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int menu_string_cancel = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int menu_string_delete = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int menu_string_delete_all = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int new_task_hint = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int ok = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int unable_to_delete = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int unable_to_save = 2131165197;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int ActionBar = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int ActionBarHomeItem = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int ActionBarHomeLogo = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int ActionBarItem = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int ActionBarProgressBar = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int BottomActionBar = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int ClearButton = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int MyTheme = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int Theme_Splash = 2131230728;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ActionBar_title = 0;
			
			private Styleable()
			{
			}
		}
	}
}
